name: Native Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Needed to upload assets to a release

jobs:
  native-build:
    name: Native Image Build
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME="${GITHUB_REF##*/}"         # e.g., v1.2.3
          VERSION="${TAG_NAME#v}"              # Strip the 'v' prefix
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          components: native-image
          cache: maven
          native-image-job-reports: true

      - name: Verify GraalVM Environment
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          if [[ -z "$GRAALVM_HOME" ]]; then
            echo "❌ GRAALVM_HOME is not set. Runner may be misconfigured."
            exit 1
          fi
          if ! command -v native-image &> /dev/null; then
            echo "❌ native-image command not found."
            exit 1
          fi
          java --version
          native-image --version

      - name: Build Native Image
        run: mvn -Pnative native:compile

      - name: List target directory
        run: ls -lh target/

      - name: Upload Native Image to Existing Release
        run: |
          ASSET_PATH="target/graalpy-sentiment"  # <--- replace with your actual file name
          if [[ ! -f "$ASSET_PATH" ]]; then
            echo "❌ Expected binary '$ASSET_PATH' not found."
            exit 1
          fi
          echo "✅ Uploading $ASSET_PATH to release $RELEASE_TAG"
          gh release upload "$RELEASE_TAG" "$ASSET_PATH" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
