name: Native Build

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: ['*'] 

permissions:
  contents: write  # Needed to upload assets to a release

jobs:
  native-build:
    name: Native Image Build
    runs-on: self-hosted

    steps:
      - name: Checkout source for release commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Validate tag and set variables
        run: |
          REF="${{ github.event.workflow_run.head_branch || github.event.workflow_run.event }}"
          # Extract the tag name from ref
          TAG=$(echo "$REF" | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
          if [[ -z "$TAG" ]]; then
            echo "❌ Unable to determine tag from workflow context."
            exit 1
          fi
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid tag format: $TAG"
            exit 1
          fi
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Get release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.RELEASE_TAG;
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            });
            core.setOutput('upload_url', release.data.upload_url);
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          native-image-job-reports: true

      - name: Verify GraalVM Environment
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          if [[ -z "$GRAALVM_HOME" ]]; then
            echo "❌ GRAALVM_HOME is not set. Runner may be misconfigured."
            exit 1
          fi
          if ! command -v native-image &> /dev/null; then
            echo "❌ native-image command not found."
            exit 1
          fi
          java --version
          native-image --version

      - name: Build Native Image
        run: mvn -Pnative native:compile

      - name: List contents of target directory
        run: ls -lh ./target/

      - name: Upload Native Image Asset
        id: upload-native-asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/graalpy-sentiment
          asset_name: graalpy-sentiment
          asset_content_type: application/octet-stream
