name: Native Build

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

permissions:
  contents: write  # Needed to upload assets to a release

jobs:
  native-build:
    name: Native Image Build
    runs-on: self-hosted

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          run-id: ${{ github.event.workflow_run.id }}
          path: ./artifacts
          merge-multiple: true
      
      - name: List contents of artifacts
        run: |
          echo "Listing contents of downloaded artifacts:"
          ls -R ./artifacts    
      - name: Download tag-name artifact
        uses: actions/download-artifact@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          name: tag-name
          run-id: ${{ github.event.workflow_run.id }}
          path: ./artifacts

      - name: Load tag name
        run: |
          TAG_NAME=$(cat tag_name.txt)
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Download upload_url artifact
        uses: actions/download-artifact@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
        with:
          name: upload-url
          run-id: ${{ github.event.workflow_run.id }}
          path: ./artifacts

      - name: Load upload URL
        run: |
          UPLOAD_URL=$(cat upload_url.txt)
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Checkout source for tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}

      # Step 4: Setup GraalVM
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          components: native-image
          cache: maven
          native-image-job-reports: true

      - name: Verify GraalVM Environment
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          if [[ -z "$GRAALVM_HOME" ]]; then
            echo "❌ GRAALVM_HOME is not set. Runner may be misconfigured."
            exit 1
          fi
          if ! command -v native-image &> /dev/null; then
            echo "❌ native-image command not found."
            exit 1
          fi
          java --version
          native-image --version

      - name: Build Native Image
        run: mvn -Pnative native:compile

      - name: List contents of target directory
        run: ls -lh ./target/

      - name: Upload Native Image Asset
        id: upload-native-asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./target/graalpy-sentiment
          asset_name: graalpy-sentiment
          asset_content_type: application/octet-stream
